In [1]:
import numpy as np
import pandas as pd
from scipy.stats import ttest_ind
from scipy.stats import f_oneway
from scipy.stats import chi2_contingency

In [2]:
#Connect colabs dengan drive
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [3]:
# Membaca file csv dan menampilkan dalam bentuk tabel
df = pd.read_excel(r'/content/drive/MyDrive/Kuliah/foundation/Manager Salary Survey 2021-FINAL (2).xlsx')
display(df)

time    age                       industry  \
0     2021-04-27 11:02:09.743  25-34   Education (Higher Education)   
1     2021-04-27 11:02:21.562  25-34              Computing or Tech   
2     2021-04-27 11:02:38.125  25-34  Accounting, Banking & Finance   
3     2021-04-27 11:02:40.643  25-34                     Nonprofits   
4     2021-04-27 11:02:41.793  25-34  Accounting, Banking & Finance   
...                       ...    ...                            ...   
27869 2023-02-27 06:22:35.240  25-34              Computing or Tech   
27870 2023-03-01 09:43:37.098  45-54       Property or Construction   
27871 2023-03-06 18:16:18.899  25-34              Behavioral Health   
27872 2023-03-09 09:11:48.506  18-24              Computing or Tech   
27873 2023-03-12 14:32:04.060  25-34              Recruitment or HR   

                                      job_title need_additional_context  \
0            Research and Instruction Librarian                     NaN   
1      Change & Internal Communications Manager                     NaN   
2                          Marketing Specialist                     NaN   
3                               Program Manager                     NaN   
4                            Accounting Manager                     NaN   
...                                         ...                     ...   
27869                     Sr software engineer                      NaN   
27870                          Property Manager                  Senior   
27871                   Mental Health Therapist                     NaN   
27872               Help Desk Associate Analyst                     NaN   
27873                             HR generalist                     NaN   

       salary  monetary_compentation currency indicate_currency  \
0       55000                    0.0      USD               NaN   
1       54600                 4000.0      GBP               NaN   
2       34000                    NaN      USD               NaN   
3       62000                 3000.0      USD               NaN   
4       60000                 7000.0      USD               NaN   
...       ...                    ...      ...               ...   
27869  190000                14000.0      USD               NaN   
27870   55000                13000.0      USD               NaN   
27871   52416                    NaN      USD               NaN   
27872   36000                    NaN      USD               NaN   
27873   60000                    NaN      USD               NaN   

      income_additional_contex         country        US_state          city  \
0                          NaN   United States   Massachusetts        Boston   
1                          NaN  United Kingdom             NaN     Cambridge   
2                          NaN              US       Tennessee   Chattanooga   
3                          NaN             USA       Wisconsin     Milwaukee   
4                          NaN              US  South Carolina    Greenville   
...                        ...             ...             ...           ...   
27869                      NaN  United States            Texas        Dallas   
27870                      NaN   United States            Ohio     Brunswick   
27871                      NaN             USA        Virginia  Spotsylvania   
27872                      NaN   United States        Illinois       Chicago   
27873                      NaN              US      California   Diamond bar   

      work_experience_overall work_experince_field hights_education_complate  \
0                   5-7 years            5-7 years           Master's degree   
1                8 - 10 years            5-7 years            College degree   
2                 2 - 4 years          2 - 4 years            College degree   
3                8 - 10 years            5-7 years            College degree   
4                8 - 10 years            5-7 years            College degree   
...                      

### **Uji t-test**

Hipotesis

*   Hipotesis null: Tidak ada perbedaan signifikan antara gaji karyawan pria dan wanita.
*   Hipotesis alternatif : Terdapat perbedaan signifikan antara gaji karyawan pria dan wanita

### **Penjelasan**


*   Kode di bawah digunakan untuk memisahkan data gaji karyawan laki-laki dan perempuan dari dataset, lalu melakukan uji statistik t-test antara kedua kelompok tersebut.
* t_stat adalah nilai statistik uji t, yang menunjukkan seberapa jauh nilai rata-rata kedua kelompok data berbeda dalam satuan standar error. 
*  p_val (atau nilai p) adalah probabilitas bahwa perbedaan antara rata-rata kedua kelompok data tidak signifikan secara statistik. Semakin kecil nilai p_val, semakin signifikan perbedaan antara rata-rata kedua kelompok data.
*   Hasil kode di atas menunjukkan nilai t_stat sebesar 0.8458312715345003 dan nilai p_val sebesar 0.3976579476045651





In [4]:
# Memisahkan data gaji karyawan pria dan wanita
male_salary = df[df['gender']=='Man']['salary']
female_salary = df[df['gender']=='Woman']['salary']

# Melakukan uji statistik t-test
t_stat, p_val = ttest_ind(male_salary, female_salary, equal_var=False)

print("t-statistic: ", t_stat)
print("p-value: ", p_val)

t-statistic:  0.8458312715345003
p-value:  0.3976579476045651


### **Penjelasan**


*   Kode di bawah digunakan untuk memisahkan data gaji karyawan laki-laki dan perempuan dari dataset, lalu melakukan uji statistik t-test antara kedua kelompok tersebut.
* t_stat adalah nilai statistik uji t, yang menunjukkan seberapa jauh nilai rata-rata kedua kelompok data berbeda dalam satuan standar error. 
*  p_val (atau nilai p) adalah probabilitas bahwa perbedaan antara rata-rata kedua kelompok data tidak signifikan secara statistik. Semakin kecil nilai p_val, semakin signifikan perbedaan antara rata-rata kedua kelompok data.
*   Hasil kode di atas menunjukkan nilai t_stat sebesar 0.8458312715345003 dan nilai p_val sebesar 0.3976579476045651





In [5]:
level_of_significance = 0.05 # Tingkat signifikansi

if p_val < level_of_significance:
    print("Hipotesis nol ditolak. Terdapat perbedaan signifikan antara gaji karyawan pria dan wanita.")
else:
    print("Hipotesis nol diterima. Tidak ada perbedaan signifikan antara gaji karyawan pria dan wanita.")

Hipotesis nol diterima. Tidak ada perbedaan signifikan antara gaji karyawan pria dan wanita.


## **Anova Test**

*   Hipotesis null: Tidak ada hubungan antara gender dan kategori gaji pada karyawan dengan pengalaman bekerja.
*   Hipotesis alternatif: Terdapat hubungan antara gender dan kategori gaji pada karyawan dengan pengalaman bekerja



## **Penjelasan Anova Test**

*   Kode 1 sampai 8 digunakan untuk memisahkan data gaji karyawan berdasarkan pengalaman kerja (work experience) yaitu "1 year or less, 2 - 4 years,  5-7 years, 8 - 10 years, 11 - 20 years, 21 - 30 years, 31 - 40 years, 41 years or more" dan jenis kelamin (gender) laki-laki (man) dan perempuan (woman). 
*   Dilakukan pengelompokan data gaji berdasarkan kategori work experience dan gender, kemudian disimpan dalam variabel-variabel yang mewakili gaji karyawan pria dan wanita pada setiap kategori work experience. Selanjutnya, variabel-variabel tersebut digunakan sebagai argumen dalam fungsi f_oneway untuk melakukan uji statistik ANOVA.
*   f_oneway digunakan untuk melakukan uji statistik ANOVA pada data gaji yang telah dibagi-bagi berdasarkan kategori work experience dan gender. 
*   Hasil dari kode di atas yaitu F-statistic menghasilkan nilai sebesar 3.485432858154642 dan p-value menghasilkan nilai sebesar 5.149148438764387e-06

In [6]:
# Memisahkan data gaji karyawan pria dan wanita untuk setiap tingkat pendidikan tertinggi
#kode1
one_or_less_salary = df[df['work_experience_overall']=="1 year or less"]
male_one_or_less_salary = one_or_less_salary[one_or_less_salary['gender']=='Man']['USD Salary']
female_one_or_less_salary = one_or_less_salary[one_or_less_salary['gender']=='Woman']['USD Salary']

#kode2
two_four_salary = df[df['work_experience_overall']=='2 - 4 years']
male_two_four_salary = two_four_salary[two_four_salary['gender']=='Man']['USD Salary']
female_two_four_salary = two_four_salary[two_four_salary['gender']=='Woman']['USD Salary']

#kode3
five_to_seven_salary = df[df['work_experience_overall']=='5-7 years']
male_five_to_seven_salary = five_to_seven_salary[five_to_seven_salary['gender']=='Man']['USD Salary']
female_five_to_seven_salary = five_to_seven_salary[five_to_seven_salary ['gender']=='Woman']['USD Salary']

#kode4
eight_to_ten_salary = df[df['work_experience_overall']=='8 - 10 years']
male_eight_to_ten_salary = eight_to_ten_salary[eight_to_ten_salary['gender']=='Man']['USD Salary']
female_eight_to_ten_salary = eight_to_ten_salary[eight_to_ten_salary ['gender']=='Woman']['USD Salary']

#kode5
eleven_to_twenty_salary = df[df['work_experience_overall']=='11 - 20 years']
male_eleven_to_twenty_salary = eleven_to_twenty_salary[eleven_to_twenty_salary['gender']=='Man']['USD Salary']
female_eleven_to_twenty_salary = eleven_to_twenty_salary[eleven_to_twenty_salary ['gender']=='Woman']['USD Salary']

#kode6
twentyone_to_thrity_salary = df[df['work_experience_overall']=='21 - 30 years']
male_twentyone_to_thrity_salary = twentyone_to_thrity_salary[twentyone_to_thrity_salary['gender']=='Man']['USD Salary']
female_twentyone_to_thrity_salary = twentyone_to_thrity_salary[twentyone_to_thrity_salary ['gender']=='Woman']['USD Salary']

#kode7
thrityone_to_fourty_salary = df[df['work_experience_overall']=='31 - 40 years']
male_thrityone_to_fourty_salary = thrityone_to_fourty_salary[thrityone_to_fourty_salary['gender']=='Man']['USD Salary']
female_thrityone_to_fourty_salary = thrityone_to_fourty_salary[thrityone_to_fourty_salary ['gender']=='Woman']['USD Salary']

#kode8
fourtyone_or_more_salary = df[df['work_experience_overall']=='41 years or more']
male_fourtyone_or_more_salary = fourtyone_or_more_salary[fourtyone_or_more_salary['gender']=='Man']['USD Salary']
female_fourtyone_or_more_salary = fourtyone_or_more_salary[fourtyone_or_more_salary ['gender']=='Woman']['USD Salary']

# Melakukan uji statistik ANOVA
f_stat, p_val = f_oneway(male_one_or_less_salary,female_one_or_less_salary,male_two_four_salary,female_two_four_salary,
                         male_five_to_seven_salary,female_five_to_seven_salary, male_eight_to_ten_salary, female_eight_to_ten_salary, 
                         male_eleven_to_twenty_salary, female_eleven_to_twenty_salary, male_twentyone_to_thrity_salary, female_twentyone_to_thrity_salary,
                         male_thrityone_to_fourty_salary, female_thrityone_to_fourty_salary, male_fourtyone_or_more_salary, 
                         male_fourtyone_or_more_salary)

print("F-statistic: ", f_stat)
print("p-value: ", p_val)

F-statistic:  3.485432858154642
p-value:  5.149148438764387e-06


## **Penjelasan Anova Test**

*    level of significance ditetapkan sebagai 0,05, yang berarti jika nilai p yang dihasilkan dari uji statistik ANOVA lebih kecil dari 0,05, hipotesis nol akan ditolak.
*   Setelah dibandingkan antara p-value dengan level of significance ternyata hasil p-value lebih kecil dibandingkan dengan level of significance.
*   Apabila p-value < level of significance maka dapat disimpulkan bahwa terdapat perbedaan yang signifikan dalam gaji karyawan antara karyawan pria dan wanita pada berbagai tingkat pendidikan tertinggi.
*   Item daftar

In [7]:
# Define alpha level (significance level)
level_of_significance = 0.05

if p_val < level_of_significance:
    print('Nilai p-value lebih kcil dari level_of_significance. Maka hipotesis nol dapat di tolak.')
    print('Terdapat hubungan antara gender dan kategori gaji pada karyawan dengan pengalaman bekerja.')
else:
    print('Nilai p-value lebih kcil dari level_of_significance. Maka hipotesis nol tidak berhasil di tolak.')
    print('Tidak ada hubungan antara gender dan kategori gaji pada karyawan dengan pengalaman bekerja.')

Nilai p-value lebih kcil dari level_of_significance. Maka hipotesis nol dapat di tolak.
Terdapat hubungan antara gender dan kategori gaji pada karyawan dengan pengalaman bekerja.


## **Chi-Square test**
*   Hipotesis nol: Tidak terdapat hubungan antara tingkat pendidikan dan gaji yang diterima.
*   Hipotesis Alternatif: Terdapat hubungan antara tingkat pendidikan dan gaji yang diterima.



## **Penjelasan Chi-Square**
*   observed adalah variabel yang digunakan untuk membuat tabel kontingensi dari dua variabel, yaitu hights_education_complate dan USD Salary. Variabel pertama (df['hights_education_complate']) dijadikan sebagai baris dan variabel kedua (df['USD Salary']) dijadikan sebagai kolom pada tabel kontingensi.
*   chi2 adalah Statistik uji chi-square yang dihasilkan dari fungsi chi2_contingency. Statistik ini akan digunakan untuk menghitung nilai p-value dari uji chi-square.
*   p-value adalah nilai hasil uji chi-square yang dihasilkan dari fungsi chi2_contingency. P-value adalah nilai probabilitas bahwa hasil uji chi-square yang diperoleh adalah acak belaka.
*   dof (degree of freedom) adalah Derajat kebebasan dari hasil uji chi-square yang dihasilkan dari fungsi chi2_contingency. Derajat kebebasan adalah jumlah variabel dikurangi 1.
*   expected adalah Tabel kontingensi yang diharapkan dari kedua variabel yang diuji, jika tidak ada hubungan antara keduanya. Variabel ini dihasilkan dari fungsi chi2_contingency.

In [8]:
from scipy.stats import chi2_contingency

# Menyiapkan data untuk uji chi-square
observed = pd.crosstab(df['hights_education_complate'], df['USD Salary'])

# Uji chi-square
chi2, p_value, dof, expected = chi2_contingency(observed)

print("expected: ",expected)
print("dof: ",dof)
print("chi2: ",chi2)
print("p value: ",p_value)

# Cetak hasil uji chi-square
if p_value < 0.05:
    print("Hipotesis H0 ditolak. Terdapat hubungan antara tingkat pendidikan dan gaji yang diterima.")
else:
    print("Hipotesis H0 diterima. Tidak terdapat hubungan antara tingkat pendidikan dan gaji yang diterima.")


expected:  [[7.28337491 0.48555833 0.48555833 ... 0.48555833 0.48555833 0.48555833]
 [0.3410693  0.02273795 0.02273795 ... 0.02273795 0.02273795 0.02273795]
 [4.78093482 0.31872899 0.31872899 ... 0.31872899 0.31872899 0.31872899]
 [0.7705238  0.05136825 0.05136825 ... 0.05136825 0.05136825 0.05136825]
 [0.71629975 0.04775332 0.04775332 ... 0.04775332 0.04775332 0.04775332]
 [1.10779742 0.07385316 0.07385316 ... 0.07385316 0.07385316 0.07385316]]
dof:  23160
chi2:  27877.397386024673
p value:  1.7277799335975983e-94
Hipotesis H0 ditolak. Terdapat hubungan antara tingkat pendidikan dan gaji yang diterima.
